# Site settings
title: Minh8
description: Minh8
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Minh Đào
user_title: Code
email: daonhatminh1978@gmail.com
github_username:  minh8

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
